### ISSUE TITLE
Remove all CSS3 mixins and rely on Autoprefixer (in any of it's flavours)/

### ISSUE THREAD

**Issue by sturobson** [sturobson/Sassifaction#2]
Personally I don't use any of the CSS3 mixins that provide prefixes where needed in Sassifaction anymore. 
As I'm predominantly using Mixture I utilise the autoprefixer option. 
There's also other flavours of autoprefixer for things like Gulp and Grunt.

The decision to be made is - 

remove all CSS3 (vender prefixing) mixins or leave 'as they are' for others.

**Comment by quasiperfect** [comment]
+1 on remove (gulp here)

**Comment by terryupton** [comment]
+1 remove here as I use Mixture and/or would use a task runner if I ever get one setup.

**Comment by mrdavefoy** [comment]
+1 on remove. I use Autoprefix in Mixture to add vendor prefixing. Removing those mixins would make everything cleaner/tidier.

**Comment by sturobson** [comment]
Ok, so this is looking positive. To clarify the scss files I'll be looking to get rid of are -

backface-visibility, box-shadow, box-sizing, flexbox, gradients, transform and transition.

The prefixes will be removed from the mixin for border-radius.

To move forward: I'll make a branch for this to work on, leaving this issue open for a couple more days before PR'ing and closing.

Any more thoughts are gratefully received.

**Comment by craigsssmith** [comment]
+1 for removing them. The less you have to maintain has to be a good thing

**Comment by sturobson** [comment]
Ok, I've been fast and loose with this, rather than branching out and creating a pull request I've just ripped them out and commited to master. 

I need to:
make a start on 'the docs'
updated 'the docs'
create a changelog
