### ISSUE TITLE
Why are all the button mixins in partials?

### ISSUE THREAD

**Issue by mxdubois** [sturobson/Sassifaction#21]
See:
https://github.com/sturobson/Sassifaction/blob/master/sass/partials/buttons/_buttons.scss

Generally partials output styles when imported, no?

Just curious :)

**Comment by sturobson** [comment]
Hi,

no outputted styles here, that'd only happen if you @include them.

Here's a quick test - http://sassmeister.com/gist/e4c9f8f7de89fe2c5139
