### ISSUE TITLE
Ability to define multiple values in the remit mixin

### ISSUE THREAD

**Issue by terryupton** [sturobson/Sassifaction#3]
We have spoken of this but thought I would add it to make it 'official' but the ability to use the remit mixin to define multiple values would be a huge win for me.

I don't think it is far off as it seems to work ok for the rems but it has issues with the pixel fallback. 

An example of how I would like to use it;

@include remit(padding, 0, 10, 5, 10) or 
@include remit(padding, 5, 10)

rather than

@include remit(padding-top, 10)
@include remit(padding-left, 4)
@include remit(padding-right, 12)
@include remit(padding-bottom, 4)

any thoughts?

**Comment by sturobson** [comment]
Hi @terryupton this is now merged from a pull request from another developer

https://github.com/sturobson/Sassifaction/pull/5
