### ISSUE TITLE
how to set margins and paddings best with the mixins available

### ISSUE THREAD

**Issue by sturobson** [sturobson/Sassifaction#4]
I got an email with some questions regarding padding and margin whilst using Sassifaction

```
    --------------------------------------------------------------------------------------------------
```

Got a quick (newbie) question if I may? Thanks in advance for your time. :)
It’s to do with the best method of setting padding and margin on elements. I can see there are a few ways to do it in Sassifcation.
1. Typography mixin - obviously applied solely to type and only affects margin and line-height.
2. Maths mixin - the remit function allows you to create, say, a margin-bottom in rems with px fallback.
3. RWD padding and margin mixin - various mixing for creating pixel-less padding and margins.

Can I ask how you typically apply margins and padding to non-type elements? Do you generally use the RWD padding and margin mixin? If so can you help me figure out how to use it? It’s the $content variable I can’t figure out how to use?
Or do you just use the remit mixin, if it’s for something like vertical margins which require rems with px fallback? I can see how both would be appropriate, but the RWD more appropriate for horizontal padding?

**Comment by sturobson** [comment]
For all vertical alignment and spacing I tend to use the typography mixin and then for anything that's not type I use remit. I very much go with CSSWizardry's http://csswizardry.com/2012/06/single-direction-margin-declarations/ post and only apply margin to the bottom of any element. 

If I need to apply anything horizontally I either 'hard code' this or use the padding & margin mixins.

Of course if I need to support OldIE I use the mixin to set the widths differently because Sassifaction uses box-sizing: border-box;

**Comment by mrdavefoy** [comment]
Cheers Stu. It was me who asked the question via email so thanks for taking the time to answer. 

One follow-up question: vertical spacing follows a vertical rhythm, based on base font size and line height. What about horizontal spacing (e.g. horizontal padding within a block element like a well)? Do you tend to base these on multiples of units, like with vertical spacing? Maybe your gutter width? I notice you don't have that set as a variable (I think?)

**Comment by NickToye** [comment]
Can I ask how come you use rwd-padding-margin mixin for creating pixel-less padding and margins?  I tend to just use a rem function to convert mine.

**Comment by sturobson** [comment]
I'm just testing this
