### ISSUE TITLE
Lowercase _placeholder.SCSS extension

### ISSUE THREAD

**Issue by KittyGiraudel** [sturobson/Sassifaction#8]
The file extension for `_placeholder.SCSS` is currently in upper case, making the syntax highlighter from GitHub fail. Moreover, file extensions should be in lower case.

**Comment by sturobson** [comment]
Ah, this'd be something I missed when setting up the files. I've got OSX to auto-capitalise SCSS and also stop over capitalisation of Sass. Will fix.
